management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
spring:
  rabbitmq:
    password: guest
    port: 5672
    host: localhost
    username: guest
  data:
    mongodb:
      port: '27017'
      host: localhost
      username: portal-todo-db
      database: todo
      password: test123
  cloud:
    stream:
      bindings:
        readFromEventTopic:
          destination: eventTopic
        writeToEventTopic:
          destination: eventTopic
      default:
        contentType: application/json


  application:
    name: todo
  jmx:
    default-domain: todo
server:
  port: '2007'
  tomcat:
    connection-timeout: 3600s
  servlet:
    session:
      timeout: 3600s
timeZone: Europe/Brussels
